#include "./initial-plan/post-cov-identify.typ"
#include "./initial-plan/post-cov-brainstorm.typ"
#include "./initial-plan/post-cov-decide.typ"
#include "./initial-plan/post-cov-cad.typ"
#include "./the-mocks-incident/identify.typ"
#include "./the-mocks-incident/decide.typ"