
#include "./one-offs/INNOV-SUB.typ"
#include "./game-analasys/game-analasys.typ"
#include "./initial-team-management/team-management.typ"
#include "./one-offs/BuildingEthos.typ"
#include "./one-offs/V1.typ"
#include "./Drivetrain-select-edp/all.typ"
#include "./programming-approach/all.typ"
#include "./manual-update1/manual-update.typ"//swapped sensors and manual update
#include "./mogo-mech/all.typ"
#include "./ring-edp/all.typ"
#include "./sensors-edp/all.typ"//swapped sensors and manual update
#include "./one-offs/program-showcase.typ"
#include "./JWS_autons/all.typ"
#include "./one-offs/JWSChecklist.typ"
#include "./one-offs/JWSReflection.typ"
#include "./one-offs/game-analysis-jws-semis.typ"
#include "./one-offs/V2.typ"
#include "./one-offs/decisions_after_JWS.typ"
#include "./pre-cov-rebuild/all.typ"
#include "./wall-edp/all.typ"
#include "./one-offs/COVReflection.typ"
#include "one-offs/cov-semis-analysis.typ"
#include "./one-offs/V3.typ"
#include "./post-cov/all.typ"
#include "./prog-entries/macros-edp/all.typ"
// pre stowe page?
#include "./one-offs/STOWEReflection.typ"
#include "./one-offs/ESSEXReflection.typ"
#include "one-offs/manual-update-28-01.typ"
#include "./nats-countdown/all.typ"
#include "./one-offs/V4.typ"
#include "./one-offs/NottinghamReflection.typ"
#include "./one-offs/NewcastleReflection.typ"
#include "./Version_4/all.typ"