
#include "./one-offs/INNOV-SUB.typ"
#include "./game-analasys/game-analasys.typ"
#include "./initial-team-management/team-management.typ"
#include "./Drivetrain-select-edp/all.typ"
#include "./programming-approach/all.typ"
#include "./sensors-edp/all.typ"
#include "./mogo-mech/all.typ"
#include "./manual-update1/manual-update.typ"
#include "./ring-edp/all.typ"
#include "./one-offs/program-showcase.typ"
#include "./JWS_autons/all.typ"
#include "./one-offs/JWSChecklist.typ"
#include "./one-offs/JWSReflection.typ"
#include "./pre-cov-rebuild/all.typ"
#include "./wall-edp/all.typ"