
#include "./game-analasys/game-analasys.typ"
#include "./initial-team-management/team-management.typ"
#include "./Drivetrain-select-edp/BrainstormSolution.typ"
#include "./Drivetrain-select-edp/DecideDrivetrain.typ"
#include "./Drivetrain-select-edp/ImplementDrivetrain.typ"
#include "./programming-approach/all.typ"
#include "./mogo-mech/all.typ"
#include "./sensors-edp/all.typ"
#include "./ring-edp/all.typ"
#include "./manual-update1/manual-update.typ"
#include "./one-offs/program-showcase.typ"
#include "./JWS_autons/all.typ"
